# Nom du workflow
name: Deploy to GitHub Pages

# Déclenche le workflow à chaque push sur la branche 'main'
on:
  push:
    branches: [ main ]

# Définit les permissions pour le workflow
permissions:
  contents: read
  pages: write
  id-token: write

# Autorise une seule exécution concurrente, en annulant les précédentes
concurrency:
  group: "pages"
  cancel-in-progress: true

# Liste des "jobs" à exécuter
jobs:
  # Job pour construire le site
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupère le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Utilisez la version de Node.js que vous souhaitez

      # 3. Installe les dépendances du projet
      - name: Install dependencies
        run: npm install

      # 4. Crée un fichier .env.production à partir des secrets de GitHub
      - name: Create .env.production file
        run: |
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.VITE_EMAILJS_SERVICE_ID }}" >> .env.production
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}" >> .env.production
          echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}" >> .env.production
          
      # 5. Construit le projet pour la production (Vite utilisera automatiquement .env.production)
      - name: Build project
        run: npm run build

      # 6. Upload le dossier 'dist' comme un artefact pour le prochain job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Job pour déployer le site sur GitHub Pages
  deploy:
    # Dépend du job 'build' pour s'exécuter
    needs: build
    
    # Configure l'environnement pour GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      # 7. Déploie l'artefact sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4